version: '3.8'

services:
  app:
    build: .
    command: bundle exec rspec
    volumes:
      - .:/myapp
    ports:
      - "9292:9292"
    depends_on:
      - db
      - redis
    environment:
      RACK_ENV: test

  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ip_monitoring_test

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data:
