development:
  adapter: postgres
  database: ip_monitoring_development
  host: db
  user: postgres
  password: password

test:
  adapter: postgres
  database: ip_monitoring_test
  host: <%= ENV['POSTGRES_HOST'] || db %>
  user: postgres
  password: password

production:
  adapter: postgres
  database: ip_monitoring_production
  host: db
  user: postgres
  password: password
